version: "3.7"

services:
  db:
    image: mysql:5.7
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_USER: $DB_USER
      MYSQL_ROOT_PASSWORD: $DB_PASS
      MYSQL_DATABASE: $DB_NAME
      MYSQL_TCP_PORT: $DB_PORT
    volumes:
      - db-data:/var/lib/mysql
      - db-config:/etc/mysql
    ports:
      - "$DB_PORT:$DB_PORT"
    expose:
      - $DB_PORT
  app:
    build: .
    container_name: api_challenge_waid
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=3307
      - DB_USER=root
      - DB_PASS=pass
      - DB_NAME=api_rest_express
      - PORT=8000
      - JWT_SECRET=09f26e402586e2faa8da4c98a35f1b20d6b033c6097befa8be3486a829587fe2f90a832bd3ff9d42710a4da095a2ce285b009f0c3730cd9b8e1af3eb84df6611
    ports:
      - 8000:8000
    volumes:
      - .:/usr/app
    links:
      - db
    depends_on:
      - db
volumes:
  db-data:
  db-config: